// Mocks generated by Mockito 5.0.5 from annotations
// in lectary/test/unitTests/abstract_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;
import 'dart:io' as _i3;

import 'package:lectary/data/db/entities/abstract.dart' as _i8;
import 'package:lectary/data/db/entities/coding.dart' as _i9;
import 'package:lectary/data/db/entities/lecture.dart' as _i6;
import 'package:lectary/data/db/entities/vocable.dart' as _i7;
import 'package:lectary/data/repositories/lecture_repository.dart' as _i4;
import 'package:lectary/models/lectary_overview.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeLectaryData extends _i1.Fake implements _i2.LectaryData {}

class _FakeFile extends _i1.Fake implements _i3.File {}

/// A class which mocks [LectureRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLectureRepository extends _i1.Mock implements _i4.LectureRepository {
  MockLectureRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.LectaryData> loadLectaryData() =>
      (super.noSuchMethod(Invocation.method(#loadLectaryData, []),
          returnValue: Future<_i2.LectaryData>.value(_FakeLectaryData()))
      as _i5.Future<_i2.LectaryData>);
  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(Invocation.method(#dispose, []),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
  @override
  _i5.Future<_i3.File> downloadLecture(_i6.Lecture? lecture) =>
      (super.noSuchMethod(Invocation.method(#downloadLecture, [lecture]),
          returnValue: Future<_i3.File>.value(_FakeFile()))
      as _i5.Future<_i3.File>);
  @override
  _i5.Stream<List<_i6.Lecture>> watchAllLectures() =>
      (super.noSuchMethod(Invocation.method(#watchAllLectures, []),
          returnValue: Stream<List<_i6.Lecture>>.empty())
      as _i5.Stream<List<_i6.Lecture>>);
  @override
  _i5.Future<List<_i6.Lecture>> loadLecturesLocal() =>
      (super.noSuchMethod(Invocation.method(#loadLecturesLocal, []),
          returnValue: Future<List<_i6.Lecture>>.value(<_i6.Lecture>[]))
      as _i5.Future<List<_i6.Lecture>>);
  @override
  _i5.Future<List<_i6.Lecture>> findAllLecturesWithLang(String? langMedia) =>
      (super.noSuchMethod(
          Invocation.method(#findAllLecturesWithLang, [langMedia]),
          returnValue: Future<List<_i6.Lecture>>.value(<_i6.Lecture>[]))
      as _i5.Future<List<_i6.Lecture>>);
  @override
  _i5.Future<int> insertLecture(_i6.Lecture? lecture) =>
      (super.noSuchMethod(Invocation.method(#insertLecture, [lecture]),
          returnValue: Future<int>.value(0)) as _i5.Future<int>);
  @override
  _i5.Future<void> updateLecture(_i6.Lecture? lecture) =>
      (super.noSuchMethod(Invocation.method(#updateLecture, [lecture]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> deleteLecture(_i6.Lecture? lecture) =>
      (super.noSuchMethod(Invocation.method(#deleteLecture, [lecture]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> deleteAllLectures() =>
      (super.noSuchMethod(Invocation.method(#deleteAllLectures, []),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
  @override
  _i5.Future<List<_i7.Vocable>> findVocablesByLangMedia(String? langMedia) =>
      (super.noSuchMethod(
          Invocation.method(#findVocablesByLangMedia, [langMedia]),
          returnValue: Future<List<_i7.Vocable>>.value(<_i7.Vocable>[]))
      as _i5.Future<List<_i7.Vocable>>);
  @override
  _i5.Future<List<_i7.Vocable>> findVocablesByLectureIdAndLangMedia(
      int? lectureId, String? langMedia) =>
      (super.noSuchMethod(
          Invocation.method(
              #findVocablesByLectureIdAndLangMedia, [lectureId, langMedia]),
          returnValue: Future<List<_i7.Vocable>>.value(<_i7.Vocable>[]))
      as _i5.Future<List<_i7.Vocable>>);
  @override
  _i5.Future<List<_i7.Vocable>> findVocablesByLecturePackAndLangMedia(
      String? lecturePack, String? langMedia) =>
      (super.noSuchMethod(
          Invocation.method(#findVocablesByLecturePackAndLangMedia,
              [lecturePack, langMedia]),
          returnValue: Future<List<_i7.Vocable>>.value(<_i7.Vocable>[]))
      as _i5.Future<List<_i7.Vocable>>);
  @override
  _i5.Future<List<_i7.Vocable>> findVocablesByLectureId(int? lectureId) =>
      (super.noSuchMethod(
          Invocation.method(#findVocablesByLectureId, [lectureId]),
          returnValue: Future<List<_i7.Vocable>>.value(<_i7.Vocable>[]))
      as _i5.Future<List<_i7.Vocable>>);
  @override
  _i5.Future<List<int>> insertVocables(List<_i7.Vocable>? vocables) =>
      (super.noSuchMethod(Invocation.method(#insertVocables, [vocables]),
          returnValue: Future<List<int>>.value(<int>[]))
      as _i5.Future<List<int>>);
  @override
  _i5.Future<void> updateVocable(_i7.Vocable? vocable) =>
      (super.noSuchMethod(Invocation.method(#updateVocable, [vocable]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> updateVocables(List<_i7.Vocable>? vocables) =>
      (super.noSuchMethod(Invocation.method(#updateVocables, [vocables]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> deleteVocablesByLectureId(int? lectureId) => (super
      .noSuchMethod(Invocation.method(#deleteVocablesByLectureId, [lectureId]),
      returnValue: Future<void>.value(null),
      returnValueForMissingStub: Future.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> deleteAllVocables() =>
      (super.noSuchMethod(Invocation.method(#deleteAllVocables, []),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> deleteAllVocablesByLangMedia(String? langMedia) =>
      (super.noSuchMethod(
          Invocation.method(#deleteAllVocablesByLangMedia, [langMedia]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> resetAllVocableProgress() =>
      (super.noSuchMethod(Invocation.method(#resetAllVocableProgress, []),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
  @override
  _i5.Future<_i3.File> downloadAbstract(_i8.Abstract? abstract) =>
      (super.noSuchMethod(Invocation.method(#downloadAbstract, [abstract]),
          returnValue: Future<_i3.File>.value(_FakeFile()))
      as _i5.Future<_i3.File>);
  @override
  _i5.Future<List<_i8.Abstract>> findAllAbstracts() =>
      (super.noSuchMethod(Invocation.method(#findAllAbstracts, []),
          returnValue: Future<List<_i8.Abstract>>.value(<_i8.Abstract>[]))
      as _i5.Future<List<_i8.Abstract>>);
  @override
  _i5.Future<int> insertAbstract(_i8.Abstract? abstract) =>
      (super.noSuchMethod(Invocation.method(#insertAbstract, [abstract]),
          returnValue: Future<int>.value(0)) as _i5.Future<int>);
  @override
  _i5.Future<void> updateAbstract(_i8.Abstract? abstract) =>
      (super.noSuchMethod(Invocation.method(#updateAbstract, [abstract]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> deleteAbstract(_i8.Abstract? abstract) =>
      (super.noSuchMethod(Invocation.method(#deleteAbstract, [abstract]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
  @override
  _i5.Future<_i3.File> downloadCoding(_i9.Coding? coding) =>
      (super.noSuchMethod(Invocation.method(#downloadCoding, [coding]),
          returnValue: Future<_i3.File>.value(_FakeFile()))
      as _i5.Future<_i3.File>);
  @override
  _i5.Future<List<_i9.Coding>> findAllCodings() =>
      (super.noSuchMethod(Invocation.method(#findAllCodings, []),
          returnValue: Future<List<_i9.Coding>>.value(<_i9.Coding>[]))
      as _i5.Future<List<_i9.Coding>>);
  @override
  _i5.Future<int> insertCoding(_i9.Coding? coding) =>
      (super.noSuchMethod(Invocation.method(#insertCoding, [coding]),
          returnValue: Future<int>.value(0)) as _i5.Future<int>);
  @override
  _i5.Future<void> updateCoding(_i9.Coding? coding) =>
      (super.noSuchMethod(Invocation.method(#updateCoding, [coding]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> deleteCoding(_i9.Coding? coding) =>
      (super.noSuchMethod(Invocation.method(#deleteCoding, [coding]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> deleteAllCoding() =>
      (super.noSuchMethod(Invocation.method(#deleteAllCoding, []),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
  @override
  _i5.Future<List<_i9.CodingEntry>> findAllCodingEntries() =>
      (super.noSuchMethod(Invocation.method(#findAllCodingEntries, []),
          returnValue:
          Future<List<_i9.CodingEntry>>.value(<_i9.CodingEntry>[]))
      as _i5.Future<List<_i9.CodingEntry>>);
  @override
  _i5.Future<List<_i9.CodingEntry>> findAllCodingEntriesByCodingId(
      int? codingId) =>
      (super.noSuchMethod(
          Invocation.method(#findAllCodingEntriesByCodingId, [codingId]),
          returnValue:
          Future<List<_i9.CodingEntry>>.value(<_i9.CodingEntry>[]))
      as _i5.Future<List<_i9.CodingEntry>>);
  @override
  _i5.Future<List<int>> insertCodingEntries(
      List<_i9.CodingEntry>? codingEntries) =>
      (super.noSuchMethod(
          Invocation.method(#insertCodingEntries, [codingEntries]),
          returnValue: Future<List<int>>.value(<int>[]))
      as _i5.Future<List<int>>);
  @override
  _i5.Future<void> updateCodingEntry(_i9.CodingEntry? codingEntry) =>
      (super.noSuchMethod(Invocation.method(#updateCodingEntry, [codingEntry]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> deleteCodingEntriesByCodingId(int? codingId) =>
      (super.noSuchMethod(
          Invocation.method(#deleteCodingEntriesByCodingId, [codingId]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> deleteAllCodingEntries() =>
      (super.noSuchMethod(Invocation.method(#deleteAllCodingEntries, []),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
}
