name: lectary
description: Lectary 4 - A sign language learning application

publish_to: 'none'

version: 4.2.0+420

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.0.5
  http: ^0.13.6
  floor: ^1.4.2
  path_provider: ^2.0.15
  archive: ^3.3.7
  url_launcher: ^6.1.11
  flutter_html: ^3.0.0-beta.1 # FIXME (dart3 compatibility) change back to stable version
  video_player: ^2.6.1
  carousel_slider: ^4.2.1
  shared_preferences: ^2.1.1
  country_icons: ^2.0.2
  collection: any
  package_info_plus: 4.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  floor_generator: ^1.4.2
  build_runner: ^2.4.4
  flutter_lints: ^2.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:

  uses-material-design: true

  # For details regarding adding assets,
  # see https://flutter.dev/assets-and-images

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts

  assets:
    - assets/images/

  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/lectary_icons.ttf