name: lectary
description: Lectary 4 - A sign language learning application

publish_to: 'none'

# Application version of the schema a.b.c+x.
# The build-name (a.b.c) follows semantic versioning.
# The build-number (x) uniquely identifies the artifact. We just simply reuse the build-name.
# In Android, build-name is used as versionName while build-number is used as versionCode and must be unique across all published bundles and increasing for newer ones.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.2.3+423

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ^3.41.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.0.5
  http: ^1.1.0
  floor: ^1.5.0
  path_provider: ^2.0.15
  archive: ^4.0.9
  url_launcher: ^6.1.11
  flutter_html: ^3.0.0-beta.1 # FIXME (dart3 compatibility) change back to stable version
  video_player: ^2.6.1
  carousel_slider: ^5.1.2
  shared_preferences: ^2.1.1
  country_icons: ^3.0.0
  collection: any
  package_info_plus: ^9.0.0
  device_info_plus: ^12.3.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  floor_generator: ^1.5.0
  build_runner: ^2.4.8
  flutter_lints: ^6.0.0

dependency_overrides:
  analyzer: ^6.4.1 # conflict between floor and flutter_test

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:

  uses-material-design: true

  # For details regarding adding assets,
  # see https://flutter.dev/assets-and-images

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts

  assets:
    - assets/images/

  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/lectary_icons.ttf